### ISSUE TITLE
The ios app icon is so dark

### ISSUE THREAD

**Issue by pebble2015** [nano-wallet-company/nano-wallet-ios#14]
Did you really use this app.See my ios app icons, has no one so dark.
Please just use channel icon,the white one is far better.
![image](https://user-images.githubusercontent.com/15058019/41906422-6113cc5e-7970-11e8-980d-42f66429ac3f.png)

**Comment by zackshapiro** [comment]
Submit a PR for the ability to use an alternate icon via the Settings menu?

Here's it in white – https://cl.ly/2t420X3V3L0p
