### ISSUE TITLE
Scanning QR code does not pre-fill

### ISSUE THREAD

**Issue by bibobode** [nano-wallet-company/nano-wallet-ios#21]
There's a bug in scanning QR codes where the amount doesn't read in and pre-fill. If you go to nanowallet.io and create a Receive transaction, you can put in an address and an amount and scanning it should pre-fill both in the Send screen but right now only the address pre-fills.

Here's our QR code standard
https://github.com/nanocurrency/raiblocks/wiki/URI-and-QR-Code-Standard

**Comment by bibobode** [comment]
It turns out that this issue only happens when the amount in the QR code is greater than the maximum sendable amount.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
