### ISSUE TITLE
librai_lib.a

### ISSUE THREAD

**Issue by sarmadmakhdoom** [nano-wallet-company/nano-wallet-ios#23]
First of all, you guys have done awesome work.

I was wondering, how are you generating librai_lib.a? We have changed source code of Nano to provide some extra functionality and we need to look into keys and address generation for iOS. Is there any way we can look at the implementation of private frameworks?

**Comment by zackshapiro** [comment]
Yeah, let me see if we can add that to the repos in here. I'll ping Lee

**Comment by zackshapiro** [comment]
@Plasmapower can you add that Rust lib with compilation instructions to the NWC repos please?

**Comment by PlasmaPower** [comment]
It's currently here: https://github.com/nanocurrency/rust-rai-lib/

To compile for iOS, setup [cargo-lipo](https://github.com/TimNN/cargo-lipo) then just run `cargo lipo --release`.

**Comment by sarmadmakhdoom** [comment]
Thanks, I will look into this. Much appreciated...

**Comment by sarmadmakhdoom** [comment]
It worked like a charm, I was able to edit the library for our needs. Thank you alot
