### ISSUE TITLE
New transactions not showing

### ISSUE THREAD

**Issue by feelcreative** [nano-wallet-company/nano-wallet-ios#29]
New transactions are not showing, no sign of sync in progress.

Steps:

1) Install iOS Wallet fresh from App store v1.0.1 (61)
2) Send some nano from another address (e.g. binance)
3) Open iOS Wallet app
4) Import Seed
5) Await sync
6) Shows no syncing activity but also latest transaction does not appear, transactions are in explorer
7) Minimising app and re-opening results in error message "Wallet cannot access internet .. etc etc"

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
