### ISSUE TITLE
URI's "amount" parameter interpreted as Mnano, not raw

### ISSUE THREAD

**Issue by superdarkbit** [nano-wallet-company/nano-wallet-ios#32]
The official Nano documentation encourages use of raw units for the "amount" parameter of a Nano URI string: https://developers.nano.org/docs/uri-qr-code-standard/

I tested the iOS Canoe wallet and the iOS Nano Blocks wallet--they scan QR codes and interpret the amount parameter as being in raw units. When I try with this wallet, it only seems to interpret the amount when it is in units of Mnano (NANO or Nano).

This occurs even when the "amount" parameter's value is less than the amount held in the wallet, unlike as is mentioned in this issue: https://github.com/nano-wallet-company/nano-wallet-ios/issues/21

Digging into the code, I see it takes in the amount value and considers it as Mnano. 

Relevant code:
- https://github.com/nano-wallet-company/nano-wallet-ios/blob/master/Raiblocks/SendViewController/AddressParser.swift
- https://github.com/nano-wallet-company/nano-wallet-ios/blob/master/Raiblocks/SendViewController/CodeScanViewController.swift (func scanAddress)
- https://github.com/nano-wallet-company/nano-wallet-ios/blob/master/Raiblocks/SendViewController/SendViewController.swift (func didReceiveAddress)
- https://github.com/nano-wallet-company/nano-wallet-ios/blob/master/Raiblocks/Extensions/NSDecimalNumber+Extensions.swift (var asRawValue)

**Comment by cenkalti** [comment]
When is this going to be fixed?

**Comment by zhyatt** [comment]
@cenkalti We are coordinating to have a build available soon that adds support for `nano_` addresses and also includes updates to resolve this issue. An existing, related commit can be found here: https://github.com/nano-wallet-company/nano-wallet-ios/commit/ce7286ae0bcad718ae3198f355053ca4e1c0f347

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
